import NavBar from '@/components/navBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/beddddba67.js" crossOrigin="anonymous" />
      </head>  
      <body className={inter.className}>
        <NavBar />
        {children}
        </body>
    </html>
  )
}
